OUT6 = step6_compare_nf('AgentFile','results/td3_agent.mat', ...
    'Bounds',[0.5 0.05], 'Tmax',480, 'nf_list',[1 2 20], ...
    'Seeds',42 + (0:4), 'Summary','rl', 'WavgWindow',50, ...
    'SaveFig','results/step6_compare.png');
